export default [
  {
    id: 1,
    image: "topMoist1.jpg",
    title: "Lakme",
    description: "Skin Brightening Night Creme",
    price: "288",
    orprice: "525",
  },

  {
    id: 2,
    image: "topcleanser1.jpg",
    title: "Minimalist",
    description: "Salicylic Face Wash",
    price: "284",
    orprice: "299",
  },
  {
    id: 3,
    image: "topsunscreen1.jpg",
    title: "Lakme",
    description: "Ultra Matte SPF 50 Sunscreen",
    price: "219",
    orprice: "365",
  },
  {
    id: 4,
    image: "topfaceserum.jpg",
    title: "minimalist",
    description: "Minimalist 2% Alpha Arbutin Serum",
    price: "521",
    orprice: "549",
  },
  {
    id: 5,
    image: "topserum1.jpg",
    title: "Streax Professional",
    description: "Vitariche Hair Serum 200ml",
    price: "356",
    orprice: "475",
  },

  {
    id: 6,
    image: "topshamp1.jpg",
    title: "LOreal",
    description: "Hyaluron Shampoo-340 ml",
    price: "300",
    orprice: "429",
  },
  {
    id: 7,
    image: "topcond1.jpg",
    title: "TRESemme",
    description: "Hyaluronic COnditioner-370 ml",
    price: "384",
    orprice: "549",
  },
  {
    id: 8,
    image: "topoil1.jpg",
    title: "Parachute",
    description: "JAsmine Gold Hair Oil 300 ml",
    price: "95",
    orprice: "164",
  },
  {
    id: 9,
    image: "tophairgel1.jpg",
    title: "Livon",
    description: "Style Pro Styling Gel-100 ml",
    price: "399",
    orprice: "665",
  },
  {
    id: 10,
    image: "moist9.jpg",
    title: "Rice Ceramide",
    description: "The face shop rice & ceramide moisturizing Emulsion 150ml",
    price: "820",
    orprice: "890",
    category: "Moisturizer",
  },
];
